/*
 * YunX (云析) - A network drive share-link parser and high-speed downloader for Android.
 * Copyright (C) 2026 CYQawa
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

// fork 分发用固定 release 签名：CI runner 不同会导致 debug keystore 每次变化、
// 跨版本无法覆盖安装。这里读取随仓库公开的 keystore.properties（fork 专用，非官方发布密钥）。
val keystoreProperties = java.util.Properties().apply {
    runCatching { load(file("keystore.properties").inputStream()) }
}

android {
    namespace = "com.yunx.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunx.app"
        minSdk = 23
        targetSdk = 34
        // 与上游 CYQawa/YunX 版本号对齐；fork 构建在 versionName 后加 "-gh<n>" 后缀以区分。
        // versionCode：历史 gh1~gh3 均为 10（当时未同步递增），自 gh4 起每次 fork 发版 +1（gh4=11, gh5=12, gh6=13, gh7=14, gh8=15, gh9=16, gh10=17, gh11=18, gh12=19, gh13=20, gh14=21）
        versionCode = 21
        versionName = "1.2.6-gh14"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        getByName("debug") {
            storeFile = file("../debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
        // 固定 release 签名：跨版本可覆盖安装（仅当 keystore.properties 存在时配置，
        // 本地未配置时 release 变体回退到 debug 签名，不阻断构建）。
        if (keystoreProperties.isNotEmpty()) {
            create("release") {
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
        // Release 变体：R8 代码混淆 + 资源压缩瘦身；用固定 release 签名（见上），跨版本可覆盖安装。
        // 注意：R8 可能误删反射/序列化类，已在 proguard-rules.pro 补 Room 等 keep 规则。
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.findByName("release") ?: signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    buildFeatures {
        compose = true
    }

    testOptions {
        // 单元测试中 android.util.Log 等桩方法返回默认值（否则一调用就抛 "Stub!"）
        unitTests.isReturnDefaultValues = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation(libs.material)   // 原 libs.material.color.utilities -> 改为官方 Material 主库（含 color.utilities 包）

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    // GFM Markdown 渲染（README 富文本）
    implementation(libs.markdownRenderer)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation("junit:junit:4.13.2")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)

    // 强制 kotlin-stdlib 与项目 Kotlin 2.1.0 对齐，避免第三方库（如 mikepenz）
    // 传递引入更高版本 stdlib 导致 "compiled with an incompatible version of Kotlin"。
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    }
}